name: Build and Test

on:
  push:
    branches:
      - weather_integration


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'  
      
      - name: Get secrets and run Flutter command
        run: |
          cd $GITHUB_WORKSPACE/test_app
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> $GITHUB_ENV
          pwd
          flutter pub get
          flutter build apk
      

